### PR TITLE
purpose description aligned with glassfrog (1.1a)

### PR DESCRIPTION
**Pull request by KoenVeltman**
In glassfrog (on the role page behind the question mark next to purpose on the top left) there is a pragmatic description of what a purpose is that I hear frequently quoted. propose to add it here for clarity and alignment with real life practice.

### CODE REVIEW

**Comment by brianjrobertson** [comment]
Koen:  This pull request has no change around purpose within it, but just a change of wording in §4.1 (dropping "You must" in the duties of transparency).  Did you submit the wrong branch, or maybe overwrite some earlier changes you made with a later change?

**Comment by KoenVeltman** [comment]
Hi Brian, somehow I dont get it to work properly. the "you must" was indeed one of the changes. If I click above here on the first commit "purpose aligned..." then I do see the change I wanted to make in 1.1a.

**Comment by brianjrobertson** [comment]
Yes, I see that too, but the final version here has that change dropped; perhaps you overwrote that change with your later commit on June 29th?  I'm not enough of an expert on using git or github to help you much here I'm sorry to say...

**Comment by brianjrobertson** [comment]
Closing this pull request until you can figure out how to re-submit; sorry!

**Pull request closed without merging**
