### PR TITLE
Update Holacracy-Constitution.md

### PR DESCRIPTION
**Pull request by bernardmariechiquet**
Tensions are not needed in the title as it is not used within the description and may create confusions, as an agenda item is not necessarily a Tension.

### CODE REVIEW

**Comment by LouisChiquet** [comment]
Seconding it!

**Comment by brianjrobertson** [comment]
@bernardmariechiquet How is an agenda item not necessarily a tension?  The intent is that every agenda item in tactical represents a tension.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson a Tension is a gap between the actual expression of your Role’s Purpose and Accountabilities and your vision of their ideal potential. When I ask for help in a tactical meeting, I put an item onto the agenda, to get the space to do so. This is not necessarily a Tension.
There is a lot of confusion about the notion of Tension. People often think that turning over a problem is a way to identify tension. No, the ideal potential is not that the problem I have is solved.  
A Tension is the gap between the real situation (and I may have one or more problems) and an ideal I am aiming for (which I am not always aware of). If I say that this is a problem, it is because I feel a constraint in relation to an ideal that I am not yet necessarily aware of. If I stay on the mental level of the problem and aim for an ideal that would be "the problem is solved", I miss the beautiful nudge that is Tension, once I understand this concept. To develop the leadership and creative capacity of each person.

**Comment by brianjrobertson** [comment]
I'm not sure I'm totally understanding/following you here, though I am getting that we perhaps are holding different definitions of Tension.  I'd consider virtually every tactical agenda item as just a placeholder for a Tension to resolve.  Perhaps Slack might be a useful forum to move this discussion to, so other coaches can easily join?  I'd love to understand the definition of Tension you're using/teaching and the strengths and weaknesses of using it compared to the definition I've been using/teaching.

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I'm using the definition in the constitution. https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#131-processing-tensions

**Comment by bernardmariechiquet** [comment]
Tension is a gap between the actual expression of your Role’s Purpose and Accountabilities and your vision of their ideal potential.

So if every tactical agenda item is just a placeholder for a Tension to resolve, The person should be aware of this ideal potential. This is not the case in so many items brought to the agenda. For example, if I ask for help, I am not necessarily aware of the ideal I am pursuing. Understanding what I don't understand is not waht I would call an ideal potential.
There may be an underlying ideal potential, of course, but it is not always conscious. So per the definition of Tension, this thing is not Tension. And more often than not, it doesn't bother, it's not useful to have further in the process of consciousness. I want to treat this thing.

**Comment by brianjrobertson** [comment]
I know, me too, but I think we have different interpretations of it.  I'd interpret virtually all tactical meeting agenda items to fit that definition, thus I teach that Tactical Meeting triage is all about processing tensions, and each agenda item is a Tension...

**Comment by brianjrobertson** [comment]
Interesting.  I would still interpret that as a Tension, because there is an ideal one is sensing, even if they aren't fully consciously aware of what it is.  But I see how the definition is ambiguous and I understand your interpretation.  I'm going to open a new ticket to broaden the definition of Tension to resolve this.

**Comment by bernardmariechiquet** [comment]
Tension is not a problem by definition.
So solving the problem is not solving a tension. That's why there are two different words, and also two different energies: reactive versus creative.

A problem is probably a barrier towards an ideal not yet discovered. But to say that the ideal would be the problem solved, is not a rigorous definition of what an ideal is.
Many people confuse the two in the use of the word tension.

This is a major issue for all those who want to contribute to developing the leadership of everyone, to model a mode of operation from "reacting to a problem" to "creating towards an ideal".

**Comment by bernardmariechiquet** [comment]
I agree that there is often confusion, which has led some clients to clarify this term of tension in the form of a constitutional amendment.

**Comment by klaas1979** [comment]
Thank you for the insights into tensions. We teach tensions to be problems or chances, because we do not want to just reach for zero from the negative side but to reach to positive infinity. New business chances are often not problems but new opportunities to be sized, we call it chances. In our teaching we say tension=problem is true but partial, because the tension=chance part is overlooked.

**Comment by bernardmariechiquet** [comment]
Tension is definitively not a problem. It is a gap. Like in electricity, electrical tension.
A lot more to say on this one!

**Comment by brianjrobertson** [comment]
I'm not seeing any obvious changes to the definition of Tension that will help with this; I think it's just a matter of nuanced interpretation, and both ways of holding it and teaching it seem worthwhile to me, with pros and cons.  So, I'm going to go ahead and accept @bernardmariechiquet's change of the tactical agenda step from "Tensions" to "Items", because that's broader and should work with both interpretations.

**Pull request merged**
