### PR TITLE
hyperlinks to core roles

### PR DESCRIPTION
**Pull request by djwork**
hyperlinks to core roles

### CODE REVIEW

**Comment by djwork** [comment]
added internal section links in constitution
replaced absolute links in readme.md with relative to make working on branches more friendly

**Comment by brianjrobertson** [comment]
Hi djw - Appreciate the submission and what you're doing here, though @RashidGilanpour tells me it breaks the automatic PDF export linked in the readme, which doesn't handle some of those links.  So, would need that resolved before pulling this change (or a replacement for the PDF export link that achieves same/similar results without breaking).

**Comment by djwork** [comment]
@brianjrobertson was @RashidGilanpour saying it broke the results of "https://gitprint.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md"?

**Comment by brianjrobertson** [comment]
Yes, I believe so (unless I misunderstood him)...  Did you try it with your forked version?  Can you send me the result?

**Comment by djwork** [comment]
Nope lack of testing on my part I will try soon (have flu right now) and if possible fix

**Pull request closed without merging**
