### PR TITLE
Update Holacracy-Constitution.md

### PR DESCRIPTION
**Pull request by LouisChiquet**
Truth is, people with laptop add points even during processing points, with GlassFrog interface allowing this. I wonder the why of this? I know it's because Human can have “hot reactions”, and if you let a few minutes, just like a soufflé, it gets down and they no longer feel the tension (example of an objection, which the persons say he/she'll bring it to the agenda to process it, and 95% of the time he/she doesn't). The concrete case of why it have been added in the first place would be interesting, because “it may disrupt a bit the point which is being processed”, well, no true, as long as you have the possibility to speak you may for example ask the Secretary to see GlassFrog, so why not add a point to the agenda? I'd really love the tension at the start.
I made a proposal, re-taking for the ending part the Clarifying Questions paragraph.

### CODE REVIEW

**Comment by brianjrobertson** [comment]
Please open an Issue to request feedback on this change; I'd like to hear if anyone has seen a concrete case where this would be substantially important, or any cases where the current restriction is important.

**Comment by julianeroell** [comment]
I don't understand Louis's comment on this request. The change itself is puzzling to me: I don't see how it helps, and it creates confusion for me re: the timing and practicalities of when I am "allowed to speak".

**Comment by LouisChiquet** [comment]
@brianjrobertson : I see comments can work here, wouldn't it be simpler to have people see the change I propose/the why and comment ? I was thinking it would make doublon, but if you think it's needed, would do so.

@martinaroell : I propose you to read [3.4.5 b](https://github.com/holacracyone/Holacracy-Constitution/blob/master/Holacracy-Constitution.md#345-integrative-decision-making-process)  where the terms “_when the participant is allowed to speak_” is already in use (with Version 4.1 of the Constitution), I suppose then it's unclear for you in this part too today? I find it, for my part, pretty clear, and causing no harm.

My tension is that, very concretely, people come to meetings, with their laptop, and can add agenda items whenever they want, which is against the Constitution in my interpretation, as today it's clearly mentioned “_Participants may add additional agenda items during the meeting as well, in between the processing of any existing agenda items._”, so it'd be a step closer to reality, and allowing also people which don't have laptops to not be put aside then those who have laptops (currently a tension few people working in the production, they have “onsite” heavy computers for checking GlassFrog, but can't “move” their computer to the meeting room naturally). My first message was also to remember a bit why it have been made this way as an historic and from what I've understood, the pros and cons about not allowing to add agenda points in the Gouvernance meeting when you can speak. Do you have clarifying questions?

**Comment by brianjrobertson** [comment]
Okay, let's try comments here then.

As a Facilitator, I've often found it very useful to be able to stop people from adding agenda items immediately verbally; it often helps with some ego dynamics that can surface.  So, this change looks like a step backwards to me in that regard, although I do get the issue you're trying to solve.  Perhaps the integration is to allow the facilitator the flexibility to choose when to allow new issues added to the agenda.

**Comment by brianjrobertson** [comment]
I'm closing this request given the issue I captured above, but if you resubmit with something that allows the Facilitator to the flexibility to control it, that might work better...

**Pull request closed without merging**
