### PR TITLE
Remove the word unrealizable

### PR DESCRIPTION
**Pull request by vicp-iq**
Related to https://github.com/holacracyone/Holacracy-Constitution/issues/305

### CODE REVIEW

**Comment by LouisChiquet** [comment]
I feel like it'd be regressing, as pedagogically, being able to refer to the constitution to express the purpose, or as we say in French “Raison d'Être”, “reason to be”, is very useful for people to develop a sense of a good purpose, which isn't just doing something, but seeking a potential. Knowing also that there's “or” in the Constitution, allowing multiples options and feeling that there's no harm for it to remain that way.

**Comment by vicp-iq** [comment]
I understand what you're saying.  You're saying that my proposal is not necessary.  I agree.  I'm curious if you see a way in which my proposal causes harm in a manner that is non-reversible?

**Comment by LouisChiquet** [comment]
When facilitating meetings in clients organisations or even when virtually engaging with clients we tend, after a couple weeks, to refer to articles of the Constitution as mentioned previously. And there's a big shift on the definition of a purpose that needs to be integrated over time (and isn't easy, as it's a mindset shift), as I said in #305 and my reply before. No longer being able to interpret my present and current interpretation of what is a purpose would harm explanations I give, and also my current Holacracy practice at iGi's, as well as my understanding of purpose in the Holacracy Constitution.

**Comment by vicp-iq** [comment]
That makes sense.  I wonder if there is an alternate way to address the issue that I've experienced, which is  the perception that a circle is an inappropriate tool to address a complex issue which has many disparate stakeholders across many different functions.

**Pull request closed without merging**
