### PR TITLE
Update Holacracy-Constitution.md

### PR DESCRIPTION
**Pull request by bernardmariechiquet**
Cf https://github.com/holacracyone/Holacracy-Constitution/issues/368

### CODE REVIEW

**Comment by brianjrobertson** [comment]
I'd like this to clarify that it can change them, not just add them, for the avoidance of any potential doubt.

**Comment by brianjrobertson** [comment]
Hmm, thinking about it further, I'd like to keep to the mental model that the Anchor Circle is not really "adding" expectations onto itself (or changing them), but just clarifying what they already are (because it is external parties that effectively place expectations/Accountabilities on an entity).

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Yes, agree. An Anchor Circle may clarify accountabilities they already have due to external parties. As I am not good enough in English could you suggest an update on the Constitution.

**Comment by Aliocha-Iordanoff** [comment]
I agree and I have another example that we are currently experiencing. When 2 organizations decide to cooperate and why not place part of their governance in a common super-circle, their respective Anchore Circle becomes a sub-circle with accountabilities. I'm not sure this super-circle will become a new Anchor Circle, even though it's the larger circle.

**Comment by brianjrobertson** [comment]
Resolved [with this](https://github.com/holacracyone/Holacracy-Constitution/commit/facc96abe54ac0060aca6e9b76ae4348f6fb2780).

**Comment by bernardmariechiquet** [comment]
Top! @brianjrobertson Thanks

**Pull request closed without merging**
