### PR TITLE
change binary-gendered expressions to gender-neutral terms

### PR DESCRIPTION
**Pull request by julianeroell**
More inclusive. Easier to read.

### CODE REVIEW

**Comment by brianjrobertson** [comment]
As much as I'd love to avoid "he or she", it isn't correct english to substitute "they", which is plural, and I'd like to keep it to the technically correct english (I learned this myself when the copyeditor for my book insisted on replacing the times I had used "they" as a singular with "he or she" instead)...

**Comment by julianeroell** [comment]
Your copyeditor is wrong, then. http://en.wikipedia.org/wiki/Singular_they

Wikipedia informs me that its more common in British English than in American English. I see it in many places and use it all over my professional writing. I find it clearer and more inclusive: Not every person is "he or she".

**Comment by brianjrobertson** [comment]
I'm with you on disliking "he or she", but still not convinced this is better.  Per that Wikipedia page, quoting from a style guide:  "Where noun–pronoun disagreement can be avoided, avoid it. Where it can't be avoided, resort to it cautiously because some people will doubt your literacy . . ."

**Comment by julianeroell** [comment]
:smile: I hear you.

**Comment by julianeroell** [comment]
Here's a hack to avoid the use of singular they, while still getting rid of "he or she": https://github.com/martinroell/Holacracy-Constitution/commit/32e1c8040625018af9f8c086faf724c1f0542754 (still two usages of singular they remaining in that version, and one typo. Could this be a way? Or is it too ugly?

**Comment by brianjrobertson** [comment]
Hmm, interesting.  I like the general idea of restructuring the overall framing to avoid the need for he/she or singular they, but these particular changes introduce other grammatical issues; e.g.: in "All participants must then fill out a ballot to nominate whomever the participant believes...", there's a reference to "a ballot", but it should be "ballots" since it's "All" vs. "Each", and then saying "whomever the participant believes" is also off...

**Comment by julianeroell** [comment]
I cleaned up the "each/all" issues from my branch (https://github.com/martinroell/Holacracy-Constitution/commit/21b67d0c8e393db4d0c2ad4094c4f8bcd2858d1a), but couldn't find better replacements for the singular they (which I still like :)). I'll let it sit like that and see if a different inspiration strikes me or someone else one day.

(Comparison to H1's master is at https://github.com/holacracyone/Holacracy-Constitution/compare/master...martinroell:genderneutral)

**Pull request closed without merging**
